export const AREAS = [
  "Perungudi",
  "Sholinganallur",
  "Karapakkam",
  "Semmencheri",
  "Palavakkam",
  "Neelankarai",
  "Injambakkam",
  "Akkarai",
  "Uthandi",
  "ECR",
];

export const CATEGORIES = [
  "Water Supply",
  "Roads",
  "Drainage",
  "Street Lights",
  "Garbage",
  "EB Issues",
  "Women Safety",
  "Medical Help",
  "Parks & Recreation",
  "Encroachment",
  "Other",
];

export const METRICS = {
  totalComplaints: 4287,
  resolved: 3841,
  inProgress: 312,
  todaysComplaints: 23,
  avgResolutionDays: "4.2 days",
  satisfactionRate: "94%",
  activeVolunteers: 218,
};

export const COMPLAINTS = [
  {
    id: "TVK24001",
    complaintCode: "TVK24001",
    citizenName: "Ramesh Kumar",
    mobileNumber: "9876543210",
    area: "Sholinganallur",
    category: "Roads",
    description: "Large pothole on ECR near Sholinganallur signal causing accidents.",
    status: "Resolved",
    priority: "High",
    createdAt: "2024-03-10",
    resolvedAt: "2024-03-14",
    assignedTo: "Road Works Team",
  },
  {
    id: "TVK24002",
    complaintCode: "TVK24002",
    citizenName: "Priya Shankar",
    mobileNumber: "9876543211",
    area: "Perungudi",
    category: "Water Supply",
    description: "No water supply for the past 3 days in our apartment complex.",
    status: "In Progress",
    priority: "High",
    createdAt: "2024-03-12",
    resolvedAt: null,
    assignedTo: "CMWSSB Team",
  },
  {
    id: "TVK24003",
    complaintCode: "TVK24003",
    citizenName: "Anbu Selvan",
    mobileNumber: "9876543212",
    area: "Karapakkam",
    category: "Street Lights",
    description: "3 street lights not working near IT park junction.",
    status: "Resolved",
    priority: "Medium",
    createdAt: "2024-03-08",
    resolvedAt: "2024-03-11",
    assignedTo: "TANGEDCO Team",
  },
  {
    id: "TVK24004",
    complaintCode: "TVK24004",
    citizenName: "Meena Devi",
    mobileNumber: "9876543213",
    area: "Semmencheri",
    category: "Drainage",
    description: "Drain overflowing onto road causing health hazard near market.",
    status: "Pending",
    priority: "High",
    createdAt: "2024-03-13",
    resolvedAt: null,
    assignedTo: null,
  },
  {
    id: "TVK24005",
    complaintCode: "TVK24005",
    citizenName: "Karthik Raj",
    mobileNumber: "9876543214",
    area: "Palavakkam",
    category: "Garbage",
    description: "Garbage not collected for a week. Smell is affecting residents.",
    status: "In Progress",
    priority: "Medium",
    createdAt: "2024-03-11",
    resolvedAt: null,
    assignedTo: "GCC Sanitation",
  },
];

export const UPDATES = [
  {
    id: 1,
    title: "ECR Road Widening – Phase 1 Completed",
    area: "ECR",
    date: "2024-03-10",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=250&fit=crop",
    description:
      "The first phase of ECR road widening between Palavakkam and Sholinganallur has been successfully completed, improving traffic flow for over 50,000 daily commuters.",
    slug: "ecr-road-widening-phase-1",
  },
  {
    id: 2,
    title: "New Street Lights Installed in Semmencheri",
    area: "Semmencheri",
    date: "2024-03-07",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop",
    description:
      "LED street lights have been installed at 45 key locations in Semmencheri, improving night-time safety for residents.",
    slug: "semmencheri-street-lights",
  },
  {
    id: 3,
    title: "Karapakkam Park Renovation",
    area: "Karapakkam",
    date: "2024-03-05",
    status: "In Progress",
    image: "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=400&h=250&fit=crop",
    description:
      "Major renovation work underway at the Karapakkam neighbourhood park, including new play equipment, seating, and walking path.",
    slug: "karapakkam-park-renovation",
  },
  {
    id: 4,
    title: "Water Pipeline Replacement – Perungudi",
    area: "Perungudi",
    date: "2024-03-01",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=250&fit=crop",
    description:
      "Old water pipelines in Perungudi replaced with new HDPE pipes, resolving chronic water supply issues affecting 1,200 households.",
    slug: "perungudi-water-pipeline",
  },
];

export const GALLERY_ITEMS = [
  {
    id: 1,
    title: "Sholinganallur Main Road Repair",
    description: "Major pothole repair and resurfacing of the main road connecting Sholinganallur to ECR.",
    category: "Roads",
    date: "2024-02-20",
    beforeImage: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop",
    area: "Sholinganallur",
  },
  {
    id: 2,
    title: "Karapakkam Drain Clearing",
    description: "Complete desilting and wall repair of the main drainage channel in Karapakkam.",
    category: "Drainage",
    date: "2024-02-10",
    beforeImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=600&h=400&fit=crop",
    area: "Karapakkam",
  },
  {
    id: 3,
    title: "Perungudi Area Street Lighting",
    description: "Installation of 30 new LED street lights along the residential streets of Perungudi.",
    category: "Street Lights",
    date: "2024-01-25",
    beforeImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    area: "Perungudi",
  },
  {
    id: 4,
    title: "Semmencheri Community Water Tank",
    description: "New overhead water tank constructed to resolve chronic water shortage in North Semmencheri.",
    category: "Water Supply",
    date: "2024-01-15",
    beforeImage: "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop",
    area: "Semmencheri",
  },
  {
    id: 5,
    title: "ECR Beach Cleanliness Drive",
    description: "Large-scale beach clean-up involving 200 volunteers across 5km of ECR coastline.",
    category: "Cleanliness",
    date: "2024-01-10",
    beforeImage: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    area: "ECR",
  },
  {
    id: 6,
    title: "Palavakkam Park Restoration",
    description: "Complete restoration of the Palavakkam neighbourhood park with new benches, lighting, and walking path.",
    category: "Other Works",
    date: "2023-12-20",
    beforeImage: "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=600&h=400&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    area: "Palavakkam",
  },
];

export const POLLS = [
  {
    id: 1,
    title: "Which area needs road repair most urgently?",
    area: "All Areas",
    endDate: "2024-03-31",
    totalVotes: 1247,
    options: [
      { id: 1, label: "Sholinganallur Main Road", votes: 430 },
      { id: 2, label: "Perungudi Junction", votes: 298 },
      { id: 3, label: "Karapakkam IT Corridor", votes: 312 },
      { id: 4, label: "Semmencheri Housing Board", votes: 207 },
    ],
  },
  {
    id: 2,
    title: "What service improvement is your top priority?",
    area: "Shollinganallur",
    endDate: "2024-04-15",
    totalVotes: 832,
    options: [
      { id: 1, label: "Water Supply Reliability", votes: 312 },
      { id: 2, label: "Better Street Lighting", votes: 187 },
      { id: 3, label: "Garbage Collection Frequency", votes: 201 },
      { id: 4, label: "Park & Green Spaces", votes: 132 },
    ],
  },
];

export const SCHEMES = [
  {
    id: 1,
    title: "CM Housing Scheme (CMHP)",
    category: "Housing",
    description: "Free housing for economically weaker sections and low-income groups in urban areas.",
    eligibility: "Annual income below ₹2.5 lakhs, no existing pucca house",
    documents: ["Aadhar Card", "Ration Card", "Income Certificate", "Residence Proof"],
    applyLink: "#",
  },
  {
    id: 2,
    title: "Kalaignar Magalir Urimai Thogai",
    category: "Women Welfare",
    description: "Monthly financial assistance of ₹1000 for women heads of households.",
    eligibility: "Woman head of household, resident of Tamil Nadu",
    documents: ["Aadhar Card", "Bank Account", "Ration Card"],
    applyLink: "#",
  },
  {
    id: 3,
    title: "Pudhumai Penn Scheme",
    category: "Education",
    description: "₹1000/month for girl students from government schools pursuing higher education.",
    eligibility: "Girl students from government schools, pursuing UG/diploma",
    documents: ["Aadhar Card", "School Certificate", "College Admission Proof"],
    applyLink: "#",
  },
  {
    id: 4,
    title: "Free Bus Pass for Students",
    category: "Transport",
    description: "Free MTC bus pass for students in government and aided schools and colleges.",
    eligibility: "Students enrolled in government or aided institutions",
    documents: ["Student ID", "Aadhar Card", "Institution Certificate"],
    applyLink: "#",
  },
];

export const VOLUNTEERS = [
  {
    id: 1,
    name: "Arun Murugan",
    area: "Sholinganallur",
    skills: ["Social Work", "Event Management"],
    joinedDate: "2023-06-15",
    status: "Active",
    completedTasks: 24,
  },
  {
    id: 2,
    name: "Kavitha Rajan",
    area: "Perungudi",
    skills: ["Communication", "Documentation"],
    joinedDate: "2023-08-10",
    status: "Active",
    completedTasks: 18,
  },
  {
    id: 3,
    name: "Senthil Kumar",
    area: "Karapakkam",
    skills: ["Technical", "Photography"],
    joinedDate: "2023-09-20",
    status: "Active",
    completedTasks: 31,
  },
];

export const MAP_AREAS = [
  { id: 1, name: "Perungudi", lat: 12.9481, lng: 80.2437, complaints: 42, resolved: 38, color: "#39a852" },
  { id: 2, name: "Sholinganallur", lat: 12.9010, lng: 80.2279, complaints: 67, resolved: 55, color: "#f3b316" },
  { id: 3, name: "Karapakkam", lat: 12.9060, lng: 80.2310, complaints: 31, resolved: 29, color: "#39a852" },
  { id: 4, name: "Semmencheri", lat: 12.8920, lng: 80.2200, complaints: 58, resolved: 43, color: "#f3b316" },
  { id: 5, name: "ECR", lat: 12.8700, lng: 80.2450, complaints: 24, resolved: 22, color: "#39a852" },
];
